/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenerationsRouteImport } from './routes/generations'
import { Route as IndexRouteImport } from './routes/index'

const GenerationsRoute = GenerationsRouteImport.update({
  id: '/generations',
  path: '/generations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generations': typeof GenerationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generations': typeof GenerationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generations': typeof GenerationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generations'
  id: '__root__' | '/' | '/generations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerationsRoute: typeof GenerationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/generations': {
      id: '/generations'
      path: '/generations'
      fullPath: '/generations'
      preLoaderRoute: typeof GenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerationsRoute: GenerationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
