/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerationsGenerationsRouteImport } from './routes/_generations/generations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsGenerationsRoute = GenerationsGenerationsRouteImport.update({
  id: '/_generations/generations',
  path: '/generations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generations': typeof GenerationsGenerationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generations': typeof GenerationsGenerationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_generations/generations': typeof GenerationsGenerationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generations'
  id: '__root__' | '/' | '/_generations/generations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerationsGenerationsRoute: typeof GenerationsGenerationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_generations/generations': {
      id: '/_generations/generations'
      path: '/generations'
      fullPath: '/generations'
      preLoaderRoute: typeof GenerationsGenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerationsGenerationsRoute: GenerationsGenerationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
