// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "header": {
    "Header": {
      "Logo": "Comfy<1>Star</1>"
    },
    "Navigation": {
      "Generations": "Generations"
    }
  },
  "translation": {

  }
}
