// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  translation: {
    Generations: {
      ControlPanelFooter: {
        DeleteGeneration: 'Delete generation';
        Diagnostics: 'Diagnostics';
        Rerun: 'Rerun';
      };
      SidePanel: {
        Title: 'Control Panel';
      };
    };
    Header: {
      Logo: 'Comfy<1>Star</1>';
    };
    Navigation: {
      Generations: 'Generations';
    };
  };
}
